### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by leileilin** [cambridgeltl/mop#1]
hey, thank you for sharing so wonderful work !
I wonder if you have tailored the knowledge graph for a specific task. For example, for the sentence of this task, only select the sub graph of the entity appearing in the sentence, and then divide the graph and ...  like normal processes of your paper do, Will such an experiment be better?
I hope you can help me answer it, thank you.

**Comment by mengzaiqiao** [comment]
Hi, sorry for my late response. We haven't tried to tailor the knowledge graph for a specific task. I think that could be more helpful compared with using the whole graph, but we cannot expect what/how many entities would appear in the sentence of the testing set. Also if we have can know what entity would be involved in a task, we don't need to divide the graph since that entity set will not too large.

**Comment by leileilin** [comment]
> Hi, sorry for my late response. We haven't tried to tailor the knowledge graph for a specific task. I think that could be more helpful compared with using the whole graph, but we cannot expect what/how many entities would appear in the sentence of the testing set. Also if we have can know what entity would be involved in a task, we don't need to divide the graph since that entity set will not too large.

Thank you for your response.
I have another question: do you try to fuse the information of the two knowledge maps? For example, the first knowledge map is divided into ten pieces, the second knowledge map is divided into ten pieces, and then it is executed normally according to your process.

**Comment by mengzaiqiao** [comment]
We haven't tried with two KGs, but UMLS intrinsically contains multiple KGs from different organizations. So it should be similarly applicable.
