### ISSUE TITLE
About relation of knowledge graph

### ISSUE THREAD

**Issue by helena-lena** [cambridgeltl/mop#4]
Hi, thanks for sharing your great work!

I'm trying to figure out the (entity1, relation, entity2) triplet.
In the SFull folder, "train2id.txt" file shows the triplet in id format (0, 138854, 0).
Entities can be matched with "entity2id.txt" file, but relations can't be matched with "relation2id.txt" file.
The "relation2id.txt" relation id starts from 0 to 255, while the "train2id.txt" relation id is different.

I tried to find the triplets in UMLS Metathesaurus files and SNOMED CT US Edition files.
I was able to match the entities to the CUI, but couldn't find relation between the entities.

Can you please provide the triplet's relation id as the id in "relation2id.txt" file or as vice versa?
I also want to know if the relations are from UMLS Metathesaurus or SNOMED CT US Edition. Thank you:)

**Comment by mengzaiqiao** [comment]
Hello! Thanks for your interest in our work. 
For the relation ID issue, I just checked I think there is no difference between the two files.
![image](https://user-images.githubusercontent.com/2853469/161344116-01bb7556-2619-4474-8283-de5362639bb1.png)

Due to the UMLS license issue, we cannot give you these CUI mappings. But now we have uploaded our triple generation [codes](https://github.com/cambridgeltl/mop/blob/main/src/data_preparing/generate_SFULL_triples.ipynb) for creating the "entity2id.txt" and  "relation2id.txt" files, where you can easily find these CUI mappings.

**Comment by helena-lena** [comment]
Thanks for your quick response and code sharing :)
Oh, I thought the train2id was (entity1, relation, entity2), but it was actually (entity1, entity2, relation). I got it!

To run the triple generation code, I used umls-2021AB version for MRCONSO.RRF and MRREL.RRF files.
I think it's a little bit different from yours.
What version of UMLS did you use?

**Comment by mengzaiqiao** [comment]
The version of UMLS that we used in this paper is 2020AA.

**Comment by helena-lena** [comment]
Thank you very much!
